server:
  port: 20000

spring:
  application:
    name: catalog-service

  ############ k8s Configuration ############
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP-SERVERS} # kafka 클러스터에 대한 초기 연결에 사용할 호스트
      group-id: consumer_group01
      auto-offset-reset: earliest
  ############ k8s Configuration ############

  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: test1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true  # Eureka ? ??
    fetch-registry: true        # Eureka?? ????? ?? ??? polling ??
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce.