version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test1234 # root 계정의 password
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/conf.d:/Users/2dongyeop/Developments/spring-cloud-msa/mysql/conf.d
      - ./:/Users/2dongyeop/Developments/spring-cloud-msa/mysql
