server:
  port: 8888

spring:
  application:
    name: config-service

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672 # 5672 is AMQP protocol port. 15672 is RabbitMQ UI port
#    username: guest # default value
#    password: guest # default value

#  profiles:
#    active: native # if config server target Native File System (Not Git)

  cloud:
    config:
      server:
        native:
          # http://localhost:8888/ecommerce/native <- check source properties
          search-locations: file://${user.home}/Developments/spring-cloud-config-server # Native File System Location (Not Git)
        git:
          # localhost:8888/ecommerce/default(or dev...) <- check source properties
#          uri: /Users/2dongyeop/Developments/spring-cloud-config-server # Local Git UseCase
          uri: https://github.com/2dongyeop/spring-cloud-config-server.git # Remote Git UseCase
#          username: $USERNAME # if Git Repository is PRIVATE
#          password: $PASSWORD # if Git Repository is PRIVATE

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh